/**
 * Shell-safety guards for branch names and absolute paths.
 *
 * FNXC:TaskStoreDecompose 2026-06-24-00:00:
 * Extracted from the monolithic packages/core/src/store.ts (U5 decomposition).
 * Pure behavior-invariant move: function bodies are byte-identical to their
 * pre-extraction form. store.ts re-imports these guards.
 *
 * FNXC:ShellSafety:
 * Reject branch names that would be unsafe to interpolate into a shell command.
 * The allowed set is a conservative subset of git's refname rules: alphanumerics,
 * `_`, `.`, `/`, `+`, and `-`, with the same leading/trailing/segment restrictions
 * git enforces. Any branch that fails this check is rejected before reaching the
 * shell, so no branch-name value can inject shell metacharacters.
 */
export function assertSafeGitBranchName(name: string): void {
  if (
    !name ||
    name.length > 255 ||
    name.startsWith("-") ||
    name.startsWith(".") ||
    name.startsWith("/") ||
    name.endsWith("/") ||
    name.endsWith(".") ||
    name.endsWith(".lock") ||
    name.includes("..") ||
    name.includes("@{") ||
    !/^[A-Za-z0-9._/+-]+$/.test(name)
  ) {
    throw new Error(`Unsafe git branch name: ${JSON.stringify(name)}`);
  }
}

/**
 * Reject filesystem paths that would be unsafe to interpolate into a shell
 * command. Worktree paths are generated by fusion itself and are expected to
 * be absolute, but `task.worktree` is writable via the authenticated API, so
 * validate at the shell boundary as defense-in-depth.
 */
export function assertSafeAbsolutePath(path: string): void {
  const isAbsolute = path.startsWith("/") || /^[A-Za-z]:[\\/]/.test(path);
  if (
    !path ||
    path.length > 4096 ||
    !isAbsolute ||
    path.startsWith("-") ||
    // Reject shell metacharacters, quotes, control chars, and NULs.
    /["'`$\n\r\t;&|<>()*?[\]{}\\\0]/.test(
      path.replace(/^[A-Za-z]:/, ""), // ignore the drive-letter colon on Windows
    )
  ) {
    throw new Error(`Unsafe path: ${JSON.stringify(path)}`);
  }
}
